const handleError = (err, req, res, next) =>{
    if (err instanceof sequelize.ValidationError) {
       res.status(400).send({
         message: 'Atenci贸n: Error en la validaci贸n de los datos.'
       });
    } else if (err instanceof sequelize.DatabaseError) {
       res.status(500).send({
         message: 'Atenci贸n: Error al interactuar con la base de datos.'
       });
    } else {
       res.status(500).send({
         message: 'Atenci贸n: Error interno del servidor.'
       });
    }
   }

   module.exports = handleError;